name: richii.me
favicon: null
layout_spectrum: 0.41605775873176754
typography_spectrum: 0.5690164801198989
title: richii.me
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.7362970926333219
  lightness: 0.2460144991055131
  saturation: 0.40344921057112515
  rhythmicContrast: 0.17126084910705686
purpose: []
