name: richii.me
favicon: null
layout_spectrum: 0.88652
typography_spectrum: 0.13138
title: richii.me
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#59504b'
    - '#ecd176'
    - '#070709'
    - '#ff7262'
    - '#9e241b'
  brandStrength: 0.7362970926333219
  lightness: 0.5625
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
