name: richii.me
favicon: null
layout_spectrum: 0.88652
typography_spectrum: 0.13138
title: richii.me
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#a8baba'
    - '#2b1c19'
    - '#494f35'
    - '#92688e'
  brandStrength: 0.7362970926333219
  lightness: 0.2460144991055131
  saturation: 0.40344921057112515
  rhythmicContrast: 0.17126084910705686
purpose: []
