name: richii.me
favicon: null
layout_spectrum: 0.67208
typography_spectrum: 0.13138
title: richii.me
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070c08'
    - '#f9f9f9'
    - '#b1bed2'
    - '#6e817b'
    - '#e5b448'
  brandStrength: 0
  lightness: 0.5625
  saturation: 0.625
  rhythmicContrast: 0
purpose: []
