title: richii.me
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5625
  brandStrength: 0
  rhythmicContrast: 0.25
  brandColors:
    - '#070c08'
    - '#f9f9f9'
    - '#b1bed2'
    - '#6e817b'
    - '#e5b448'
  lightness: 0.5
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: richii.me
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.13138
layout_spectrum: 0.8659359
